//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.default_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.default_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.default_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Scroll_UP
        {
            get
            {
                return SteamVR_Actions.default_Scroll_UP;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Scroll_DOWN
        {
            get
            {
                return SteamVR_Actions.default_Scroll_DOWN;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Scroll_LEFT
        {
            get
            {
                return SteamVR_Actions.default_Scroll_LEFT;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Scroll_RIGHT
        {
            get
            {
                return SteamVR_Actions.default_Scroll_RIGHT;
            }
        }
        
        public virtual SteamVR_Action_Boolean CenterClick
        {
            get
            {
                return SteamVR_Actions.default_CenterClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightClick
        {
            get
            {
                return SteamVR_Actions.default_RightClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftClick
        {
            get
            {
                return SteamVR_Actions.default_LeftClick;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
